/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/card-bill-payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Card Bill Payments */
        get: operations["card_bill_payments_api_card_bill_payments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cards */
        get: operations["cards_api_cards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{entity_id}/{issuer}/statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Card Statement */
        get: operations["card_statement_api_cards__entity_id___issuer__statement_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{entity_id}/{issuer}/statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Card Statements */
        get: operations["card_statements_api_cards__entity_id___issuer__statements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/family": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Family */
        get: operations["family_api_family_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/family/{entity_id}/{person}/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Family Transfers */
        get: operations["family_transfers_api_family__entity_id___person__transfers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/holdings/{entity_id}/{instrument_id}/diary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Holding Diary */
        get: operations["holding_diary_api_holdings__entity_id___instrument_id__diary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Everything this session has run. In memory by design (ADR-0002) — the UI says so.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /**
         * Start Job
         * @description Run a WLC verb against exactly one named, manifest-declared workspace.
         *
         *     There is no "run against all": each store has its own gates, its own key and its own lock, and a
         *     fan-out would hide which one refused.
         */
        post: operations["start_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Status */
        get: operations["job_status_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Stream
         * @description Watch a running verb as server-sent events.
         *
         *     The stream carries the verb's own narration as OPAQUE lines. Only `import` publishes structure
         *     mid-run, so parsing prose into a progress bar would mean inventing a contract that does not exist
         *     and breaking it on the next copy edit upstream. Lines now, structure when the engine offers it.
         *
         *     The stream is a convenience, never the record: the outcome stays retrievable from the job endpoint
         *     after the stream closes, so a viewer who navigates away or reconnects still learns what happened.
         */
        get: operations["job_stream_api_jobs__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/networth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Networth */
        get: operations["networth_api_networth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Performance */
        get: operations["performance_api_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Positions */
        get: operations["positions_api_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report List
         * @description What reports exist. Static — no store is opened, so the nav renders before any data loads.
         */
        get: operations["report_list_api_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report */
        get: operations["report_api_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/source/{entity_id}/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Source Detail
         * @description The provenance record behind a fact row's `source_id` — the source popup (Primitive B): what the
         *     document was, when it was captured, and which tables it wrote. An unknown id returns an empty record
         *     (every field None, no tables), not a 404, so a stale row's popup degrades to "no longer in the store"
         *     rather than erroring.
         */
        get: operations["source_detail_api_source__entity_id___source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transactions */
        get: operations["transactions_api_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload
         * @description Deposit a statement into one entity's inbox — and do nothing else with it.
         *
         *     No parsing, no store write, no look inside. Importing is a separate, explicit act with WLC's gates
         *     in front of it (ADR-0005).
         */
        post: operations["upload_api_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Engine presence and per-store versions, read at request time — never remembered (ADR-0017).
         */
        get: operations["version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workspace Detail
         * @description Where an entity's money physically lives, what state it is in, and what built it.
         */
        get: operations["workspace_detail_api_workspace__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/{entity_id}/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diagnose Statement
         * @description Describe an unrecognized statement's LAYOUT, safe to share. The diagnose verb runs in the workspace
         *     context, so it reuses WLC's OWN password resolution — the presenter duplicates no secret logic
         *     (custodian/presenter boundary, constitution #10). The result is structure only: no values, no names.
         */
        post: operations["diagnose_statement_api_workspace__entity_id__diagnose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/{entity_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open Document
         * @description Ask the OS to open ONE collateral file. WLW never reads a statement (ADR-0001) — this hands the
         *     file to the platform's opener. The path is never trusted: `collateral.resolve_document_path` refuses
         *     anything that escapes the workspace, so even a tampered filename cannot reach outside it.
         */
        post: operations["open_document_api_workspace__entity_id__open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/{entity_id}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reveal Secret
         * @description Release ONE re-obtainable secret, on an explicit request (ADR-0019).
         *
         *     Its own endpoint, deliberately: a value must never be reachable by asking for a list. There is no
         *     equivalent for the store key, and there will not be — it cannot be re-obtained.
         */
        post: operations["reveal_secret_api_workspace__entity_id__reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/{entity_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Settings
         * @description Change one setting. Everything bootstrap asks is editable here (identity-and-settings).
         */
        post: operations["change_settings_api_workspace__entity_id__settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Availability
         * @description Why a workspace can or cannot be read right now. The order is the order a caller should check.
         * @enum {string}
         */
        Availability: "ok" | "no_engine" | "missing" | "busy" | "schema_skew" | "unreadable";
        /** Body_upload_api_upload_post */
        Body_upload_api_upload_post: {
            /** Entity */
            entity: string;
            /** File */
            file: string;
            /** Workspace */
            workspace?: string | null;
        };
        /**
         * CardBillPaymentRow
         * @description A credit-card bill payment on the bank statement — the bank→card drill-down.
         */
        CardBillPaymentRow: {
            /** @description ₹ paid (positive) */
            amount: components["schemas"]["Money"];
            /**
             * Bank
             * @description The account the payment left from
             */
            bank?: string | null;
            /** Date */
            date?: string | null;
            /** Entity Id */
            entity_id?: string | null;
            /** Entity Label */
            entity_label?: string | null;
            /**
             * Issuer
             * @description The card, identified by the amount or the narration
             */
            issuer?: string | null;
            /** Narration */
            narration?: string | null;
            /**
             * Resolved
             * @description True when the card's statement is loaded and openable
             */
            resolved: boolean;
            /**
             * Statement Date
             * @description The bill this settled — the drill target, when the card is loaded
             */
            statement_date?: string | null;
        };
        /** CardBillPayments */
        CardBillPayments: {
            /**
             * Excluded
             * @default []
             */
            excluded: components["schemas"]["Excluded"][];
            /**
             * Granularity
             * @constant
             */
            granularity: "card_payments";
            /** Is Partial */
            is_partial: boolean;
            provenance: components["schemas"]["Provenance"];
            /** Reporting Currency */
            reporting_currency: string;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["CardBillPaymentRow"][];
        };
        /**
         * CardRow
         * @description One credit card in the picker, tagged with whose store it came from.
         */
        CardRow: {
            /** Account Id */
            account_id: string;
            /** Entity Id */
            entity_id?: string | null;
            /** Entity Label */
            entity_label?: string | null;
            /** Issuer */
            issuer: string;
            /**
             * Last Statement
             * @description Closing date of the newest statement
             */
            last_statement?: string | null;
            /** @description The newest statement's new balance — ₹ owed */
            outstanding?: components["schemas"]["Money"] | null;
            /**
             * Since
             * @description Date of the first transaction on record
             */
            since?: string | null;
            /**
             * Statements
             * @description How many statements are loaded for this card
             */
            statements: number;
        };
        /**
         * CardStatement
         * @description One card statement, itemised — the current-month view.
         */
        CardStatement: {
            /** Entity Id */
            entity_id: string;
            /** Issuer */
            issuer: string;
            new_balance?: components["schemas"]["Money"] | null;
            previous_balance?: components["schemas"]["Money"] | null;
            provenance: components["schemas"]["Provenance"];
            /** Statement Date */
            statement_date?: string | null;
            /**
             * Transactions
             * @default []
             */
            transactions: components["schemas"]["CardStatementLine"][];
        };
        /** CardStatementLine */
        CardStatementLine: {
            /** @description Signed: a purchase is negative, a payment/credit positive */
            amount: components["schemas"]["Money"];
            /** Created At */
            created_at?: string | null;
            /** Created By */
            created_by?: string | null;
            /** Date */
            date?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "spend" | "payment";
            /**
             * Funded By Bank
             * @description For a payment line: the bank account that funded it
             */
            funded_by_bank?: string | null;
            /** Funded By Date */
            funded_by_date?: string | null;
            /** Source Id */
            source_id?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Updated By */
            updated_by?: string | null;
        };
        /**
         * CardStatementSummary
         * @description One statement in a card's history — the period selector, each row self-summarising.
         */
        CardStatementSummary: {
            new_balance?: components["schemas"]["Money"] | null;
            /** @description Σ credits and bill payments this period */
            payments: components["schemas"]["Money"];
            previous_balance?: components["schemas"]["Money"] | null;
            /** @description Σ purchases this period */
            spends: components["schemas"]["Money"];
            /** Statement Date */
            statement_date?: string | null;
            /** Transactions */
            transactions: number;
        };
        /** CardStatements */
        CardStatements: {
            /** Entity Id */
            entity_id: string;
            /** Issuer */
            issuer: string;
            /**
             * Statements
             * @default []
             */
            statements: components["schemas"]["CardStatementSummary"][];
        };
        /** Cards */
        Cards: {
            /**
             * Excluded
             * @default []
             */
            excluded: components["schemas"]["Excluded"][];
            /**
             * Granularity
             * @constant
             */
            granularity: "cards";
            /** Is Partial */
            is_partial: boolean;
            provenance: components["schemas"]["Provenance"];
            /** Reporting Currency */
            reporting_currency: string;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["CardRow"][];
        };
        /** ClassTotal */
        ClassTotal: {
            /** Asset Class */
            asset_class: string;
            /**
             * Basis
             * @description How WealthLens-core valued this line
             */
            basis?: string | null;
            value: components["schemas"]["Money"];
        };
        /**
         * Deposit
         * @description Where an uploaded statement landed. A deposit, not an import — nothing was parsed.
         */
        Deposit: {
            /** Entity Id */
            entity_id: string;
            /** Filename */
            filename: string;
            /** Inbox */
            inbox: string;
            /**
             * Renamed From
             * @description Set when a name collided: both files are kept, never overwritten
             */
            renamed_from?: string | null;
        };
        /**
         * DiagnoseBundle
         * @description The safe-to-share diagnostic for an unrecognized statement — STRUCTURE ONLY, no values, names, or ids.
         *     The on-ramp a user hands to their AI agent, or reads alongside the 'Add your bank' guide.
         */
        DiagnoseBundle: {
            /** Filename */
            filename: string;
            /**
             * Fingerprint
             * @description A stable id for this layout — same format, same id
             */
            fingerprint?: string | null;
            /**
             * Needs Ocr
             * @description True when scanned pages carry content no text parser reads
             * @default false
             */
            needs_ocr: boolean;
            /** Pages */
            pages?: number | null;
            /**
             * Report
             * @description The masked layout report — every value replaced by its shape
             */
            report: string;
            /**
             * Scanned
             * @default 0
             */
            scanned: number;
        };
        /**
         * DiaryLine
         * @description One line of a holding's CAS transcript. Balances are UNIT quantities, not money.
         */
        DiaryLine: {
            /** Action */
            action?: string | null;
            /**
             * Booked
             * @description True when this line reached the quantity ledger
             */
            booked: boolean;
            /** Closing */
            closing?: number | null;
            /** Created At */
            created_at?: string | null;
            /** Created By */
            created_by?: string | null;
            /** Credit */
            credit?: number | null;
            /** Date */
            date?: string | null;
            /** Debit */
            debit?: number | null;
            /** Description */
            description?: string | null;
            /** Free */
            free?: number | null;
            /** Line Kind */
            line_kind: string;
            /** Locked */
            locked?: number | null;
            /** Pledged */
            pledged?: number | null;
            /**
             * Role
             * @description Why the line did/didn't move ownership
             */
            role?: string | null;
            /** Source Id */
            source_id?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Updated By */
            updated_by?: string | null;
        };
        /** DocumentInfo */
        DocumentInfo: {
            /** Captured At */
            captured_at?: string | null;
            /** Filename */
            filename?: string | null;
            /** Kind */
            kind: string;
            password: components["schemas"]["PasswordRef"];
            /** Payload Ref */
            payload_ref?: string | null;
            /**
             * Period End
             * @description Statement period end / statement date
             */
            period_end?: string | null;
            /**
             * Period Start
             * @description Statement period start, when the source records one
             */
            period_start?: string | null;
            /** Provider */
            provider?: string | null;
            /** Rows */
            rows?: number | null;
            /** Source Id */
            source_id: string;
        };
        /** EngineInfo */
        EngineInfo: {
            /** Detail */
            detail?: string | null;
            /** Present */
            present: boolean;
            /** Schema Version */
            schema_version?: string | null;
        };
        /** EntityTotal */
        EntityTotal: {
            /**
             * By Class
             * @default []
             */
            by_class: components["schemas"]["ClassTotal"][];
            /** Contributes */
            contributes: boolean;
            /** Entity Id */
            entity_id: string;
            /**
             * Evidence As Of
             * @description Newest DOCUMENT evidence — not the date the view was computed at
             */
            evidence_as_of?: string | null;
            /** Excluded Reason */
            excluded_reason?: string | null;
            /** Label */
            label: string;
            /**
             * Owner
             * @description Whose beneficial share these figures are valued for
             */
            owner: string;
            /** Owner Warning */
            owner_warning?: string | null;
            /**
             * Status
             * @default ok
             * @enum {string}
             */
            status: "ok" | "stale" | "excluded";
            total?: components["schemas"]["Money"] | null;
            /**
             * Workspaces
             * @default []
             */
            workspaces: components["schemas"]["WorkspaceInfo"][];
        };
        /** Excluded */
        Excluded: {
            /** Entity Id */
            entity_id: string;
            /** Label */
            label: string;
            /** Owner Warning */
            owner_warning?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** Family */
        Family: {
            /**
             * Excluded
             * @default []
             */
            excluded: components["schemas"]["Excluded"][];
            /**
             * Granularity
             * @constant
             */
            granularity: "family";
            /** Is Partial */
            is_partial: boolean;
            provenance: components["schemas"]["Provenance"];
            /** Reporting Currency */
            reporting_currency: string;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["FamilyMemberRow"][];
        };
        /**
         * FamilyMemberRow
         * @description One household member and the money moved to them from a store.
         */
        FamilyMemberRow: {
            /**
             * Entity Id
             * @description The sending store
             */
            entity_id?: string | null;
            /** Entity Label */
            entity_label?: string | null;
            /** First Transfer */
            first_transfer?: string | null;
            /**
             * Holdings
             * @description Instruments the store attributes to this member
             * @default 0
             */
            holdings: number;
            /** Last Transfer */
            last_transfer?: string | null;
            /** Member Id */
            member_id?: string | null;
            /** Name */
            name?: string | null;
            /** Relationship */
            relationship?: string | null;
            total: components["schemas"]["Money"];
            /**
             * Transfers
             * @default 0
             */
            transfers: number;
        };
        /** FamilyTransfers */
        FamilyTransfers: {
            /** Entity Id */
            entity_id: string;
            /** Person */
            person: string;
            provenance: components["schemas"]["Provenance"];
            /**
             * Transfers
             * @default []
             */
            transfers: components["schemas"]["TransferRow"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Holder */
        Holder: {
            /**
             * Ours
             * @description True only when this app started the process — never inferred
             */
            ours: boolean;
            /** Pid */
            pid: number;
            /** Process */
            process: string;
        };
        /**
         * HoldingDiary
         * @description One holding's full detail — performance, identity lineage, and the CAS transcript.
         */
        HoldingDiary: {
            /** Entity Id */
            entity_id: string;
            /** Instrument */
            instrument: string;
            /**
             * Lineage
             * @default []
             */
            lineage: components["schemas"]["LineageEdge"][];
            /**
             * Lines
             * @default []
             */
            lines: components["schemas"]["DiaryLine"][];
            /** Name */
            name?: string | null;
            performance?: components["schemas"]["HoldingPerformance"] | null;
            provenance: components["schemas"]["Provenance"];
        };
        /**
         * HoldingPerformance
         * @description One holding's performance summary, from its cost basis. None on the drill-down when there is none.
         */
        HoldingPerformance: {
            /** Abs Return Pct */
            abs_return_pct?: number | null;
            /**
             * Corp Action
             * @description Cost & value may sit on different ISINs — approximate
             * @default false
             */
            corp_action: boolean;
            current?: components["schemas"]["Money"] | null;
            gain?: components["schemas"]["Money"] | null;
            invested?: components["schemas"]["Money"] | null;
            realised?: components["schemas"]["Money"] | null;
            /**
             * Synthetic Dates
             * @description Buy dates were inferred — XIRR is approximate
             * @default false
             */
            synthetic_dates: boolean;
            unrealised?: components["schemas"]["Money"] | null;
            /**
             * Xirr Pct
             * @description Money-weighted return
             */
            xirr_pct?: number | null;
        };
        /** Identifier */
        Identifier: {
            /**
             * Kind
             * @description 'none' is STATED, never inferred from a blank field
             * @enum {string}
             */
            kind: "isin" | "none";
            /** Value */
            value?: string | null;
        };
        /** Job */
        Job: {
            /**
             * Changed Something
             * @description False for a refusal: the store is untouched
             */
            changed_something: boolean;
            /** Entity Id */
            entity_id: string;
            /**
             * Exit Code
             * @description Recorded, never interpreted — `outcome` is the authority
             */
            exit_code?: number | null;
            /**
             * Gate
             * @description Which gate refused — branch on this, not the message
             */
            gate?: string | null;
            /** Id */
            id: string;
            /** Message */
            message?: string | null;
            outcome?: components["schemas"]["Outcome"] | null;
            /**
             * Result
             * @default {}
             */
            result: {
                [key: string]: unknown;
            };
            state: components["schemas"]["JobState"];
            /** Verb */
            verb: string;
        };
        /**
         * JobState
         * @enum {string}
         */
        JobState: "queued" | "running" | "finished";
        /**
         * LineageEdge
         * @description One recorded change in a holding's identity — a merger, demerger, or ISIN change.
         */
        LineageEdge: {
            /** Action */
            action?: string | null;
            /** Date */
            date?: string | null;
            /** From Isin */
            from_isin?: string | null;
            /** From Name */
            from_name?: string | null;
            /** Note */
            note?: string | null;
            /** Ratio */
            ratio?: string | null;
            /** To Isin */
            to_isin?: string | null;
            /** To Name */
            to_name?: string | null;
        };
        /** Money */
        Money: {
            /**
             * Amount
             * @description Exact decimal as a string — never a JSON number (see module docstring)
             */
            amount: string;
            /**
             * Currency
             * @description ISO 4217 code
             */
            currency: string;
        };
        /** NetWorth */
        NetWorth: {
            /**
             * As Of
             * @description The date the view was COMPUTED at
             */
            as_of?: string | null;
            /** Entities */
            entities: components["schemas"]["EntityTotal"][];
            /**
             * Granularity
             * @constant
             */
            granularity: "aggregate";
            /**
             * Is Partial
             * @description True when a declared entity could not be included
             */
            is_partial: boolean;
            provenance: components["schemas"]["Provenance"];
            /** Reporting Currency */
            reporting_currency: string;
            /**
             * Stale Count
             * @description Included entities answering from stale evidence
             * @default 0
             */
            stale_count: number;
            total?: components["schemas"]["Money"] | null;
        };
        /**
         * Opened
         * @description Confirmation that a collateral file was handed to the OS to open. The path is the user's own machine,
         *     already shown on this screen — returning it is feedback, not a leak.
         */
        Opened: {
            /** Path */
            path: string;
        };
        /**
         * Outcome
         * @description WLC's own vocabulary, mirrored so callers never see a raw exit code.
         * @enum {string}
         */
        Outcome: "ok" | "attention" | "refused" | "failed";
        /** PasswordRef */
        PasswordRef: {
            /**
             * Kind
             * @description THREE states, not two: named, opened-by-something-unnamed, or never opened
             * @enum {string}
             */
            kind: "named" | "unnamed" | "none";
            /** Name */
            name?: string | null;
        };
        /**
         * Performance
         * @description The portfolio, for the charts: the current value breakup and the monthly value series per class.
         *     Every figure the charts REPORT (total, share, axis ticks, stack edges) is computed here, not the UI.
         */
        Performance: {
            /** @description Growth-chart Y-axis maximum */
            axis_max?: components["schemas"]["Money"] | null;
            /**
             * Axis Ticks
             * @description Growth-chart Y-axis tick values (money labels)
             * @default []
             */
            axis_ticks: components["schemas"]["Money"][];
            /**
             * Breakup
             * @default []
             */
            breakup: components["schemas"]["PerformanceBucket"][];
            /** Reporting Currency */
            reporting_currency: string;
            /**
             * Series
             * @default []
             */
            series: components["schemas"]["PerformancePoint"][];
            /** @description Portfolio total = sum of positive buckets */
            total?: components["schemas"]["Money"] | null;
        };
        /**
         * PerformanceBucket
         * @description One asset-class slice of the current portfolio value.
         */
        PerformanceBucket: {
            /** Asset Class */
            asset_class: string;
            /**
             * Share
             * @description Percent of the positive-bucket total; computed in the bridge
             * @default 0
             */
            share: number;
            value: components["schemas"]["Money"];
        };
        /**
         * PerformancePoint
         * @description One (month, asset-class) value on the growth series, with its PRE-SUMMED stack position.
         */
        PerformancePoint: {
            /** Asset Class */
            asset_class: string;
            /** @description Cumulative stack floor below this band */
            base?: components["schemas"]["Money"] | null;
            /** Date */
            date?: string | null;
            /** @description Cumulative stack ceiling incl. this band */
            top?: components["schemas"]["Money"] | null;
            value: components["schemas"]["Money"];
        };
        /** PositionRow */
        PositionRow: {
            /** Account Id */
            account_id?: string | null;
            /** Amfi Code */
            amfi_code?: string | null;
            /** As Of */
            as_of?: string | null;
            /** Asset Class */
            asset_class?: string | null;
            /** Basis */
            basis?: string | null;
            /** Closed On */
            closed_on?: string | null;
            /** Disposition */
            disposition?: string | null;
            /** Entity Id */
            entity_id: string;
            /** Entity Label */
            entity_label: string;
            /** Fills */
            fills?: number | null;
            /** First Acquired On */
            first_acquired_on?: string | null;
            identifier: components["schemas"]["Identifier"];
            /** Instrument Id */
            instrument_id?: string | null;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Last Acquired On */
            last_acquired_on?: string | null;
            /** Last Valued On */
            last_valued_on?: string | null;
            /** Lots */
            lots?: number | null;
            /** Name */
            name?: string | null;
            /** Quantity */
            quantity?: number | null;
            /** Subtype */
            subtype?: string | null;
            value: components["schemas"]["Money"];
        };
        /** Positions */
        Positions: {
            /** As Of */
            as_of?: string | null;
            /**
             * Excluded
             * @default []
             */
            excluded: components["schemas"]["Excluded"][];
            /**
             * Granularity
             * @constant
             */
            granularity: "positions";
            /** Is Partial */
            is_partial: boolean;
            provenance: components["schemas"]["Provenance"];
            /** Reporting Currency */
            reporting_currency: string;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["PositionRow"][];
        };
        /**
         * Provenance
         * @description What an exported or printed artifact carries so a figure survives leaving the app (ADR-0013).
         */
        Provenance: {
            /**
             * As Of
             * @description The single date everything was computed at
             */
            as_of?: string | null;
            /**
             * Filters
             * @default []
             */
            filters: string[];
            /** Reporting Currency */
            reporting_currency: string;
            /** Row Count */
            row_count?: number | null;
            /**
             * Scope
             * @description Whose money this is, in words a reader outside the household can use
             */
            scope: string;
            /**
             * Stores
             * @default []
             */
            stores: string[];
            /** Title */
            title: string;
            /**
             * Warnings
             * @description What a shared date does NOT fix: exclusions, and stale evidence
             * @default []
             */
            warnings: string[];
        };
        /** Report */
        Report: {
            /** As Of */
            as_of?: string | null;
            /**
             * Excluded
             * @default []
             */
            excluded: components["schemas"]["Excluded"][];
            /** Id */
            id: string;
            /** Is Partial */
            is_partial: boolean;
            provenance: components["schemas"]["Provenance"];
            /** Reporting Currency */
            reporting_currency: string;
            /**
             * Sections
             * @default []
             */
            sections: components["schemas"]["ReportSection"][];
            /** Subtitle */
            subtitle: string;
            /** Title */
            title: string;
        };
        /** ReportSection */
        ReportSection: {
            /** Count */
            count: number;
            /** Icon */
            icon: string;
            /** Id */
            id: string;
            /** Note */
            note?: string | null;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["PositionRow"][];
            /** Title */
            title: string;
            /** @description None when the section spans currencies */
            total?: components["schemas"]["Money"] | null;
        };
        /**
         * ReportSummary
         * @description A report as it appears in the nav — no store is opened to build this.
         */
        ReportSummary: {
            /** Id */
            id: string;
            /**
             * Sections
             * @default []
             */
            sections: {
                [key: string]: string;
            }[];
            /** Subtitle */
            subtitle: string;
            /** Title */
            title: string;
        };
        /**
         * Revealed
         * @description One re-obtainable secret, released on an explicit request (ADR-0019).
         *
         *     This model exists on exactly one endpoint. Nothing that returns a list may carry it.
         */
        Revealed: {
            /** Value */
            value: string;
            /** What */
            what: string;
        };
        /** SettingsInfo */
        SettingsInfo: {
            /** Config Path */
            config_path: string;
            /**
             * Holder Names
             * @default []
             */
            holder_names: string[];
            /** Organize */
            organize: boolean;
            /**
             * Pan Set
             * @description Set or unset only — the value is never returned by any read
             */
            pan_set: boolean;
            /**
             * Secret Names
             * @default []
             */
            secret_names: string[];
        };
        /**
         * SourceDetail
         * @description One source's full provenance record — the payload behind the source popup. `detail` is the adapter's
         *     own facts (card min-due/due-date, statement period, …), shape varies by adapter. Empty object = unknown
         *     id (the popup fails soft).
         */
        SourceDetail: {
            /** Adapter */
            adapter?: string | null;
            /** Captured At */
            captured_at?: string | null;
            /**
             * Detail
             * @default {}
             */
            detail: {
                [key: string]: unknown;
            };
            /** Payload Ref */
            payload_ref?: string | null;
            /** Period End */
            period_end?: string | null;
            /** Period Start */
            period_start?: string | null;
            /** Provider */
            provider?: string | null;
            /** Row Count */
            row_count?: number | null;
            /** Source Id */
            source_id?: string | null;
            /** Source Type */
            source_type?: string | null;
            /**
             * Tables
             * @default []
             */
            tables: components["schemas"]["SourceTableCount"][];
        };
        /** SourceTableCount */
        SourceTableCount: {
            /** Rows */
            rows: number;
            /** Table */
            table: string;
        };
        /** StoreInfo */
        StoreInfo: {
            availability: components["schemas"]["Availability"];
            /** Entity Id */
            entity_id: string;
            /** Schema Version */
            schema_version?: string | null;
            /** Workspace */
            workspace: string;
        };
        /** TransactionRow */
        TransactionRow: {
            /** Account Id */
            account_id?: string | null;
            /** @description Signed: negative left the household */
            amount: components["schemas"]["Money"];
            balance?: components["schemas"]["Money"] | null;
            /** Bank */
            bank?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Created By */
            created_by?: string | null;
            /** Date */
            date?: string | null;
            /** Entity Id */
            entity_id: string;
            /** Entity Label */
            entity_label: string;
            /** Narration */
            narration?: string | null;
            /** Source Id */
            source_id?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Updated By */
            updated_by?: string | null;
        };
        /** Transactions */
        Transactions: {
            /** As Of */
            as_of?: string | null;
            /**
             * Excluded
             * @default []
             */
            excluded: components["schemas"]["Excluded"][];
            /**
             * Granularity
             * @constant
             */
            granularity: "transactions";
            /** Is Partial */
            is_partial: boolean;
            provenance: components["schemas"]["Provenance"];
            /** Reporting Currency */
            reporting_currency: string;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["TransactionRow"][];
        };
        /**
         * TransferRow
         * @description One bank transfer to a household member.
         */
        TransferRow: {
            amount: components["schemas"]["Money"];
            /** Bank */
            bank?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Created By */
            created_by?: string | null;
            /** Date */
            date?: string | null;
            /** Narration */
            narration?: string | null;
            /** Source Id */
            source_id?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Updated By */
            updated_by?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Version */
        Version: {
            engine: components["schemas"]["EngineInfo"];
            /**
             * Stores
             * @default []
             */
            stores: components["schemas"]["StoreInfo"][];
        };
        /** WorkspaceDetail */
        WorkspaceDetail: {
            /**
             * Documents
             * @default []
             */
            documents: components["schemas"]["DocumentInfo"][];
            /** Entity Id */
            entity_id: string;
            /** Path */
            path: string;
            settings: components["schemas"]["SettingsInfo"];
            workspace: components["schemas"]["WorkspaceInfo"];
        };
        /** WorkspaceInfo */
        WorkspaceInfo: {
            availability: components["schemas"]["Availability"];
            /** Detail */
            detail?: string | null;
            holder?: components["schemas"]["Holder"] | null;
            /** Label */
            label: string;
            /** Schema Version */
            schema_version?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    card_bill_payments_api_card_bill_payments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardBillPayments"];
                };
            };
        };
    };
    cards_api_cards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cards"];
                };
            };
        };
    };
    card_statement_api_cards__entity_id___issuer__statement_get: {
        parameters: {
            query?: {
                period?: string | null;
                named?: string | null;
            };
            header?: never;
            path: {
                entity_id: string;
                issuer: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardStatement"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    card_statements_api_cards__entity_id___issuer__statements_get: {
        parameters: {
            query?: {
                named?: string | null;
            };
            header?: never;
            path: {
                entity_id: string;
                issuer: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardStatements"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    family_api_family_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Family"];
                };
            };
        };
    };
    family_transfers_api_family__entity_id___person__transfers_get: {
        parameters: {
            query?: {
                named?: string | null;
            };
            header?: never;
            path: {
                entity_id: string;
                person: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyTransfers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    holding_diary_api_holdings__entity_id___instrument_id__diary_get: {
        parameters: {
            query?: {
                named?: string | null;
            };
            header?: never;
            path: {
                entity_id: string;
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingDiary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
        };
    };
    start_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_status_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_stream_api_jobs__job_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    networth_api_networth_get: {
        parameters: {
            query?: {
                on?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetWorth"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    performance_api_performance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Performance"];
                };
            };
        };
    };
    positions_api_positions_get: {
        parameters: {
            query?: {
                on?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Positions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_list_api_reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSummary"][];
                };
            };
        };
    };
    report_api_reports__report_id__get: {
        parameters: {
            query?: {
                on?: string | null;
            };
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_detail_api_source__entity_id___source_id__get: {
        parameters: {
            query?: {
                named?: string | null;
            };
            header?: never;
            path: {
                entity_id: string;
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transactions_api_transactions_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transactions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deposit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    workspace_detail_api_workspace__entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnose_statement_api_workspace__entity_id__diagnose_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnoseBundle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_document_api_workspace__entity_id__open_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Opened"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reveal_secret_api_workspace__entity_id__reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revealed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_settings_api_workspace__entity_id__settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
