/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/card-bill-payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Card Bill Payments */
        get: operations["card_bill_payments_api_card_bill_payments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cards */
        get: operations["cards_api_cards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{entity_id}/{issuer}/statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Card Statement */
        get: operations["card_statement_api_cards__entity_id___issuer__statement_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{entity_id}/{issuer}/statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Card Statements */
        get: operations["card_statements_api_cards__entity_id___issuer__statements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/holdings/{entity_id}/{instrument_id}/diary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Holding Diary */
        get: operations["holding_diary_api_holdings__entity_id___instrument_id__diary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Everything this session has run. In memory by design (ADR-0002) — the UI says so.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /**
         * Start Job
         * @description Run a WLC verb against exactly one named, manifest-declared workspace.
         *
         *     There is no "run against all": each store has its own gates, its own key and its own lock, and a
         *     fan-out would hide which one refused.
         */
        post: operations["start_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Status */
        get: operations["job_status_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Stream
         * @description Watch a running verb as server-sent events.
         *
         *     The stream carries the verb's own narration as OPAQUE lines. Only `import` publishes structure
         *     mid-run, so parsing prose into a progress bar would mean inventing a contract that does not exist
         *     and breaking it on the next copy edit upstream. Lines now, structure when the engine offers it.
         *
         *     The stream is a convenience, never the record: the outcome stays retrievable from the job endpoint
         *     after the stream closes, so a viewer who navigates away or reconnects still learns what happened.
         */
        get: operations["job_stream_api_jobs__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/networth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Networth */
        get: operations["networth_api_networth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Positions */
        get: operations["positions_api_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report List
         * @description What reports exist. Static — no store is opened, so the nav renders before any data loads.
         */
        get: operations["report_list_api_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report */
        get: operations["report_api_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transactions */
        get: operations["transactions_api_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload
         * @description Deposit a statement into one entity's inbox — and do nothing else with it.
         *
         *     No parsing, no store write, no look inside. Importing is a separate, explicit act with WLC's gates
         *     in front of it (ADR-0005).
         */
        post: operations["upload_api_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Engine presence and per-store versions, read at request time — never remembered (ADR-0017).
         */
        get: operations["version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workspace Detail
         * @description Where an entity's money physically lives, what state it is in, and what built it.
         */
        get: operations["workspace_detail_api_workspace__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/{entity_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open Document
         * @description Ask the OS to open ONE collateral file. WLW never reads a statement (ADR-0001) — this hands the
         *     file to the platform's opener. The path is never trusted: `collateral.resolve_document_path` refuses
         *     anything that escapes the workspace, so even a tampered filename cannot reach outside it.
         */
        post: operations["open_document_api_workspace__entity_id__open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/{entity_id}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reveal Secret
         * @description Release ONE re-obtainable secret, on an explicit request (ADR-0019).
         *
         *     Its own endpoint, deliberately: a value must never be reachable by asking for a list. There is no
         *     equivalent for the store key, and there will not be — it cannot be re-obtained.
         */
        post: operations["reveal_secret_api_workspace__entity_id__reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/{entity_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Settings
         * @description Change one setting. Everything bootstrap asks is editable here (identity-and-settings).
         */
        post: operations["change_settings_api_workspace__entity_id__settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Availability
         * @description Why a workspace can or cannot be read right now. The order is the order a caller should check.
         * @enum {string}
         */
        Availability: "ok" | "no_engine" | "missing" | "busy" | "schema_skew" | "unreadable";
        /** Body_upload_api_upload_post */
        Body_upload_api_upload_post: {
            /** Entity */
            entity: string;
            /** File */
            file: string;
            /** Workspace */
            workspace?: string | null;
        };
        /**
         * CardBillPaymentRow
         * @description A credit-card bill payment on the bank statement — the bank→card drill-down.
         */
        CardBillPaymentRow: {
            /** @description ₹ paid (positive) */
            amount: components["schemas"]["Money"];
            /**
             * Bank
             * @description The account the payment left from
             */
            bank?: string | null;
            /** Date */
            date?: string | null;
            /** Entity Id */
            entity_id?: string | null;
            /** Entity Label */
            entity_label?: string | null;
            /**
             * Issuer
             * @description The card, identified by the amount or the narration
             */
            issuer?: string | null;
            /** Narration */
            narration?: string | null;
            /**
             * Resolved
             * @description True when the card's statement is loaded and openable
             */
            resolved: boolean;
            /**
             * Statement Date
             * @description The bill this settled — the drill target, when the card is loaded
             */
            statement_date?: string | null;
        };
        /** CardBillPayments */
        CardBillPayments: {
            /**
             * Excluded
             * @default []
             */
            excluded: components["schemas"]["Excluded"][];
            /**
             * Granularity
             * @constant
             */
            granularity: "card_payments";
            /** Is Partial */
            is_partial: boolean;
            provenance: components["schemas"]["Provenance"];
            /** Reporting Currency */
            reporting_currency: string;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["CardBillPaymentRow"][];
        };
        /**
         * CardRow
         * @description One credit card in the picker, tagged with whose store it came from.
         */
        CardRow: {
            /** Account Id */
            account_id: string;
            /** Entity Id */
            entity_id?: string | null;
            /** Entity Label */
            entity_label?: string | null;
            /** Issuer */
            issuer: string;
            /**
             * Last Statement
             * @description Closing date of the newest statement
             */
            last_statement?: string | null;
            /** @description The newest statement's new balance — ₹ owed */
            outstanding?: components["schemas"]["Money"] | null;
            /**
             * Since
             * @description Date of the first transaction on record
             */
            since?: string | null;
            /**
             * Statements
             * @description How many statements are loaded for this card
             */
            statements: number;
        };
        /**
         * CardStatement
         * @description One card statement, itemised — the current-month view.
         */
        CardStatement: {
            /** Entity Id */
            entity_id: string;
            /** Issuer */
            issuer: string;
            new_balance?: components["schemas"]["Money"] | null;
            previous_balance?: components["schemas"]["Money"] | null;
            /** Statement Date */
            statement_date?: string | null;
            /**
             * Transactions
             * @default []
             */
            transactions: components["schemas"]["CardStatementLine"][];
        };
        /** CardStatementLine */
        CardStatementLine: {
            /** @description Signed: a purchase is negative, a payment/credit positive */
            amount: components["schemas"]["Money"];
            /** Date */
            date?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "spend" | "payment";
        };
        /**
         * CardStatementSummary
         * @description One statement in a card's history — the period selector, each row self-summarising.
         */
        CardStatementSummary: {
            new_balance?: components["schemas"]["Money"] | null;
            /** @description Σ credits and bill payments this period */
            payments: components["schemas"]["Money"];
            previous_balance?: components["schemas"]["Money"] | null;
            /** @description Σ purchases this period */
            spends: components["schemas"]["Money"];
            /** Statement Date */
            statement_date?: string | null;
            /** Transactions */
            transactions: number;
        };
        /** CardStatements */
        CardStatements: {
            /** Entity Id */
            entity_id: string;
            /** Issuer */
            issuer: string;
            /**
             * Statements
             * @default []
             */
            statements: components["schemas"]["CardStatementSummary"][];
        };
        /** Cards */
        Cards: {
            /**
             * Excluded
             * @default []
             */
            excluded: components["schemas"]["Excluded"][];
            /**
             * Granularity
             * @constant
             */
            granularity: "cards";
            /** Is Partial */
            is_partial: boolean;
            provenance: components["schemas"]["Provenance"];
            /** Reporting Currency */
            reporting_currency: string;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["CardRow"][];
        };
        /** ClassTotal */
        ClassTotal: {
            /** Asset Class */
            asset_class: string;
            /**
             * Basis
             * @description How WealthLens-core valued this line
             */
            basis?: string | null;
            value: components["schemas"]["Money"];
        };
        /**
         * Deposit
         * @description Where an uploaded statement landed. A deposit, not an import — nothing was parsed.
         */
        Deposit: {
            /** Entity Id */
            entity_id: string;
            /** Filename */
            filename: string;
            /** Inbox */
            inbox: string;
            /**
             * Renamed From
             * @description Set when a name collided: both files are kept, never overwritten
             */
            renamed_from?: string | null;
        };
        /**
         * DiaryLine
         * @description One line of a holding's CAS transcript. Balances are UNIT quantities, not money.
         */
        DiaryLine: {
            /** Action */
            action?: string | null;
            /**
             * Booked
             * @description True when this line reached the quantity ledger
             */
            booked: boolean;
            /** Closing */
            closing?: number | null;
            /** Credit */
            credit?: number | null;
            /** Date */
            date?: string | null;
            /** Debit */
            debit?: number | null;
            /** Description */
            description?: string | null;
            /** Free */
            free?: number | null;
            /** Line Kind */
            line_kind: string;
            /** Locked */
            locked?: number | null;
            /** Pledged */
            pledged?: number | null;
            /**
             * Role
             * @description Why the line did/didn't move ownership
             */
            role?: string | null;
        };
        /** DocumentInfo */
        DocumentInfo: {
            /** Captured At */
            captured_at?: string | null;
            /** Filename */
            filename?: string | null;
            /** Kind */
            kind: string;
            password: components["schemas"]["PasswordRef"];
            /** Payload Ref */
            payload_ref?: string | null;
            /** Provider */
            provider?: string | null;
            /** Rows */
            rows?: number | null;
            /** Source Id */
            source_id: string;
        };
        /** EngineInfo */
        EngineInfo: {
            /** Detail */
            detail?: string | null;
            /** Present */
            present: boolean;
            /** Schema Version */
            schema_version?: string | null;
        };
        /** EntityTotal */
        EntityTotal: {
            /**
             * By Class
             * @default []
             */
            by_class: components["schemas"]["ClassTotal"][];
            /** Contributes */
            contributes: boolean;
            /** Entity Id */
            entity_id: string;
            /**
             * Evidence As Of
             * @description Newest DOCUMENT evidence — not the date the view was computed at
             */
            evidence_as_of?: string | null;
            /** Excluded Reason */
            excluded_reason?: string | null;
            /** Label */
            label: string;
            /**
             * Owner
             * @description Whose beneficial share these figures are valued for
             */
            owner: string;
            /** Owner Warning */
            owner_warning?: string | null;
            total?: components["schemas"]["Money"] | null;
            /**
             * Workspaces
             * @default []
             */
            workspaces: components["schemas"]["WorkspaceInfo"][];
        };
        /** Excluded */
        Excluded: {
            /** Entity Id */
            entity_id: string;
            /** Label */
            label: string;
            /** Owner Warning */
            owner_warning?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Holder */
        Holder: {
            /**
             * Ours
             * @description True only when this app started the process — never inferred
             */
            ours: boolean;
            /** Pid */
            pid: number;
            /** Process */
            process: string;
        };
        /**
         * HoldingDiary
         * @description One holding's full transcript — every CAS line for it, in order (detailed_holding_diary).
         */
        HoldingDiary: {
            /** Entity Id */
            entity_id: string;
            /** Instrument */
            instrument: string;
            /**
             * Lines
             * @default []
             */
            lines: components["schemas"]["DiaryLine"][];
            /** Name */
            name?: string | null;
        };
        /** Identifier */
        Identifier: {
            /**
             * Kind
             * @description 'none' is STATED, never inferred from a blank field
             * @enum {string}
             */
            kind: "isin" | "none";
            /** Value */
            value?: string | null;
        };
        /** Job */
        Job: {
            /**
             * Changed Something
             * @description False for a refusal: the store is untouched
             */
            changed_something: boolean;
            /** Entity Id */
            entity_id: string;
            /**
             * Exit Code
             * @description Recorded, never interpreted — `outcome` is the authority
             */
            exit_code?: number | null;
            /**
             * Gate
             * @description Which gate refused — branch on this, not the message
             */
            gate?: string | null;
            /** Id */
            id: string;
            /** Message */
            message?: string | null;
            outcome?: components["schemas"]["Outcome"] | null;
            /**
             * Result
             * @default {}
             */
            result: {
                [key: string]: unknown;
            };
            state: components["schemas"]["JobState"];
            /** Verb */
            verb: string;
        };
        /**
         * JobState
         * @enum {string}
         */
        JobState: "queued" | "running" | "finished";
        /** Money */
        Money: {
            /**
             * Amount
             * @description Exact decimal as a string — never a JSON number (see module docstring)
             */
            amount: string;
            /**
             * Currency
             * @description ISO 4217 code
             */
            currency: string;
        };
        /** NetWorth */
        NetWorth: {
            /**
             * As Of
             * @description The date the view was COMPUTED at
             */
            as_of?: string | null;
            /** Entities */
            entities: components["schemas"]["EntityTotal"][];
            /**
             * Granularity
             * @constant
             */
            granularity: "aggregate";
            /**
             * Is Partial
             * @description True when a declared entity could not be included
             */
            is_partial: boolean;
            provenance: components["schemas"]["Provenance"];
            /** Reporting Currency */
            reporting_currency: string;
            total?: components["schemas"]["Money"] | null;
        };
        /**
         * Opened
         * @description Confirmation that a collateral file was handed to the OS to open. The path is the user's own machine,
         *     already shown on this screen — returning it is feedback, not a leak.
         */
        Opened: {
            /** Path */
            path: string;
        };
        /**
         * Outcome
         * @description WLC's own vocabulary, mirrored so callers never see a raw exit code.
         * @enum {string}
         */
        Outcome: "ok" | "attention" | "refused" | "failed";
        /** PasswordRef */
        PasswordRef: {
            /**
             * Kind
             * @description THREE states, not two: named, opened-by-something-unnamed, or never opened
             * @enum {string}
             */
            kind: "named" | "unnamed" | "none";
            /** Name */
            name?: string | null;
        };
        /** PositionRow */
        PositionRow: {
            /** Account Id */
            account_id?: string | null;
            /** Amfi Code */
            amfi_code?: string | null;
            /** As Of */
            as_of?: string | null;
            /** Asset Class */
            asset_class?: string | null;
            /** Basis */
            basis?: string | null;
            /** Closed On */
            closed_on?: string | null;
            /** Disposition */
            disposition?: string | null;
            /** Entity Id */
            entity_id: string;
            /** Entity Label */
            entity_label: string;
            /** Fills */
            fills?: number | null;
            /** First Acquired On */
            first_acquired_on?: string | null;
            identifier: components["schemas"]["Identifier"];
            /** Instrument Id */
            instrument_id?: string | null;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Last Acquired On */
            last_acquired_on?: string | null;
            /** Last Valued On */
            last_valued_on?: string | null;
            /** Lots */
            lots?: number | null;
            /** Name */
            name?: string | null;
            /** Quantity */
            quantity?: number | null;
            /** Subtype */
            subtype?: string | null;
            value: components["schemas"]["Money"];
        };
        /** Positions */
        Positions: {
            /** As Of */
            as_of?: string | null;
            /**
             * Excluded
             * @default []
             */
            excluded: components["schemas"]["Excluded"][];
            /**
             * Granularity
             * @constant
             */
            granularity: "positions";
            /** Is Partial */
            is_partial: boolean;
            provenance: components["schemas"]["Provenance"];
            /** Reporting Currency */
            reporting_currency: string;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["PositionRow"][];
        };
        /**
         * Provenance
         * @description What an exported or printed artifact carries so a figure survives leaving the app (ADR-0013).
         */
        Provenance: {
            /**
             * As Of
             * @description The single date everything was computed at
             */
            as_of?: string | null;
            /**
             * Filters
             * @default []
             */
            filters: string[];
            /** Reporting Currency */
            reporting_currency: string;
            /** Row Count */
            row_count?: number | null;
            /**
             * Scope
             * @description Whose money this is, in words a reader outside the household can use
             */
            scope: string;
            /**
             * Stores
             * @default []
             */
            stores: string[];
            /** Title */
            title: string;
            /**
             * Warnings
             * @description What a shared date does NOT fix: exclusions, and stale evidence
             * @default []
             */
            warnings: string[];
        };
        /** Report */
        Report: {
            /** As Of */
            as_of?: string | null;
            /**
             * Excluded
             * @default []
             */
            excluded: components["schemas"]["Excluded"][];
            /** Id */
            id: string;
            /** Is Partial */
            is_partial: boolean;
            provenance: components["schemas"]["Provenance"];
            /** Reporting Currency */
            reporting_currency: string;
            /**
             * Sections
             * @default []
             */
            sections: components["schemas"]["ReportSection"][];
            /** Subtitle */
            subtitle: string;
            /** Title */
            title: string;
        };
        /** ReportSection */
        ReportSection: {
            /** Count */
            count: number;
            /** Icon */
            icon: string;
            /** Id */
            id: string;
            /** Note */
            note?: string | null;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["PositionRow"][];
            /** Title */
            title: string;
            /** @description None when the section spans currencies */
            total?: components["schemas"]["Money"] | null;
        };
        /**
         * ReportSummary
         * @description A report as it appears in the nav — no store is opened to build this.
         */
        ReportSummary: {
            /** Id */
            id: string;
            /**
             * Sections
             * @default []
             */
            sections: {
                [key: string]: string;
            }[];
            /** Subtitle */
            subtitle: string;
            /** Title */
            title: string;
        };
        /**
         * Revealed
         * @description One re-obtainable secret, released on an explicit request (ADR-0019).
         *
         *     This model exists on exactly one endpoint. Nothing that returns a list may carry it.
         */
        Revealed: {
            /** Value */
            value: string;
            /** What */
            what: string;
        };
        /** SettingsInfo */
        SettingsInfo: {
            /** Config Path */
            config_path: string;
            /**
             * Holder Names
             * @default []
             */
            holder_names: string[];
            /** Organize */
            organize: boolean;
            /**
             * Pan Set
             * @description Set or unset only — the value is never returned by any read
             */
            pan_set: boolean;
            /**
             * Secret Names
             * @default []
             */
            secret_names: string[];
        };
        /** StoreInfo */
        StoreInfo: {
            availability: components["schemas"]["Availability"];
            /** Entity Id */
            entity_id: string;
            /** Schema Version */
            schema_version?: string | null;
            /** Workspace */
            workspace: string;
        };
        /** TransactionRow */
        TransactionRow: {
            /** Account Id */
            account_id?: string | null;
            /** @description Signed: negative left the household */
            amount: components["schemas"]["Money"];
            balance: components["schemas"]["Money"];
            /** Bank */
            bank?: string | null;
            /** Date */
            date?: string | null;
            /** Entity Id */
            entity_id: string;
            /** Entity Label */
            entity_label: string;
            /** Narration */
            narration?: string | null;
        };
        /** Transactions */
        Transactions: {
            /** As Of */
            as_of?: string | null;
            /**
             * Excluded
             * @default []
             */
            excluded: components["schemas"]["Excluded"][];
            /**
             * Granularity
             * @constant
             */
            granularity: "transactions";
            /** Is Partial */
            is_partial: boolean;
            provenance: components["schemas"]["Provenance"];
            /** Reporting Currency */
            reporting_currency: string;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["TransactionRow"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Version */
        Version: {
            engine: components["schemas"]["EngineInfo"];
            /**
             * Stores
             * @default []
             */
            stores: components["schemas"]["StoreInfo"][];
        };
        /** WorkspaceDetail */
        WorkspaceDetail: {
            /**
             * Documents
             * @default []
             */
            documents: components["schemas"]["DocumentInfo"][];
            /** Entity Id */
            entity_id: string;
            /** Path */
            path: string;
            settings: components["schemas"]["SettingsInfo"];
            workspace: components["schemas"]["WorkspaceInfo"];
        };
        /** WorkspaceInfo */
        WorkspaceInfo: {
            availability: components["schemas"]["Availability"];
            /** Detail */
            detail?: string | null;
            holder?: components["schemas"]["Holder"] | null;
            /** Label */
            label: string;
            /** Schema Version */
            schema_version?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    card_bill_payments_api_card_bill_payments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardBillPayments"];
                };
            };
        };
    };
    cards_api_cards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cards"];
                };
            };
        };
    };
    card_statement_api_cards__entity_id___issuer__statement_get: {
        parameters: {
            query?: {
                period?: string | null;
                named?: string | null;
            };
            header?: never;
            path: {
                entity_id: string;
                issuer: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardStatement"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    card_statements_api_cards__entity_id___issuer__statements_get: {
        parameters: {
            query?: {
                named?: string | null;
            };
            header?: never;
            path: {
                entity_id: string;
                issuer: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardStatements"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    holding_diary_api_holdings__entity_id___instrument_id__diary_get: {
        parameters: {
            query?: {
                named?: string | null;
            };
            header?: never;
            path: {
                entity_id: string;
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingDiary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
        };
    };
    start_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_status_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_stream_api_jobs__job_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    networth_api_networth_get: {
        parameters: {
            query?: {
                on?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetWorth"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    positions_api_positions_get: {
        parameters: {
            query?: {
                on?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Positions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_list_api_reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSummary"][];
                };
            };
        };
    };
    report_api_reports__report_id__get: {
        parameters: {
            query?: {
                on?: string | null;
            };
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transactions_api_transactions_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transactions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deposit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    workspace_detail_api_workspace__entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_document_api_workspace__entity_id__open_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Opened"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reveal_secret_api_workspace__entity_id__reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revealed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_settings_api_workspace__entity_id__settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
