/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Job
         * @description Run a WLC verb against exactly one named, manifest-declared workspace.
         *
         *     There is no "run against all": each store has its own gates, its own key and its own lock, and a
         *     fan-out would hide which one refused.
         */
        post: operations["start_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Status */
        get: operations["job_status_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Stream
         * @description Watch a running verb as server-sent events.
         *
         *     The stream carries the verb's own narration as OPAQUE lines. Only `import` publishes structure
         *     mid-run, so parsing prose into a progress bar would mean inventing a contract that does not exist
         *     and breaking it on the next copy edit upstream. Lines now, structure when the engine offers it.
         *
         *     The stream is a convenience, never the record: the outcome stays retrievable from the job endpoint
         *     after the stream closes, so a viewer who navigates away or reconnects still learns what happened.
         */
        get: operations["job_stream_api_jobs__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/networth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Networth */
        get: operations["networth_api_networth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Positions */
        get: operations["positions_api_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transactions */
        get: operations["transactions_api_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Engine presence and per-store versions, read at request time — never remembered (ADR-0017).
         */
        get: operations["version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Availability
         * @description Why a workspace can or cannot be read right now. The order is the order a caller should check.
         * @enum {string}
         */
        Availability: "ok" | "no_engine" | "missing" | "busy" | "schema_skew" | "unreadable";
        /** ClassTotal */
        ClassTotal: {
            /** Asset Class */
            asset_class: string;
            /**
             * Basis
             * @description How WealthLens-core valued this line
             */
            basis?: string | null;
            value: components["schemas"]["Money"];
        };
        /** EngineInfo */
        EngineInfo: {
            /** Detail */
            detail?: string | null;
            /** Present */
            present: boolean;
            /** Schema Version */
            schema_version?: string | null;
        };
        /** EntityTotal */
        EntityTotal: {
            /**
             * By Class
             * @default []
             */
            by_class: components["schemas"]["ClassTotal"][];
            /** Contributes */
            contributes: boolean;
            /** Entity Id */
            entity_id: string;
            /**
             * Evidence As Of
             * @description Newest DOCUMENT evidence — not the date the view was computed at
             */
            evidence_as_of?: string | null;
            /** Excluded Reason */
            excluded_reason?: string | null;
            /** Label */
            label: string;
            /**
             * Owner
             * @description Whose beneficial share these figures are valued for
             */
            owner: string;
            /** Owner Warning */
            owner_warning?: string | null;
            total?: components["schemas"]["Money"] | null;
            /**
             * Workspaces
             * @default []
             */
            workspaces: components["schemas"]["WorkspaceInfo"][];
        };
        /** Excluded */
        Excluded: {
            /** Entity Id */
            entity_id: string;
            /** Label */
            label: string;
            /** Owner Warning */
            owner_warning?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Holder */
        Holder: {
            /**
             * Ours
             * @description True only when this app started the process — never inferred
             */
            ours: boolean;
            /** Pid */
            pid: number;
            /** Process */
            process: string;
        };
        /** Identifier */
        Identifier: {
            /**
             * Kind
             * @description 'none' is STATED, never inferred from a blank field
             * @enum {string}
             */
            kind: "isin" | "none";
            /** Value */
            value?: string | null;
        };
        /** Job */
        Job: {
            /**
             * Changed Something
             * @description False for a refusal: the store is untouched
             */
            changed_something: boolean;
            /** Entity Id */
            entity_id: string;
            /**
             * Exit Code
             * @description Recorded, never interpreted — `outcome` is the authority
             */
            exit_code?: number | null;
            /**
             * Gate
             * @description Which gate refused — branch on this, not the message
             */
            gate?: string | null;
            /** Id */
            id: string;
            /** Message */
            message?: string | null;
            outcome?: components["schemas"]["Outcome"] | null;
            /**
             * Result
             * @default {}
             */
            result: {
                [key: string]: unknown;
            };
            state: components["schemas"]["JobState"];
            /** Verb */
            verb: string;
        };
        /**
         * JobState
         * @enum {string}
         */
        JobState: "queued" | "running" | "finished";
        /** Money */
        Money: {
            /**
             * Amount
             * @description Exact decimal as a string — never a JSON number (see module docstring)
             */
            amount: string;
            /**
             * Currency
             * @description ISO 4217 code
             */
            currency: string;
        };
        /** NetWorth */
        NetWorth: {
            /**
             * As Of
             * @description The date the view was COMPUTED at
             */
            as_of?: string | null;
            /** Entities */
            entities: components["schemas"]["EntityTotal"][];
            /**
             * Granularity
             * @constant
             */
            granularity: "aggregate";
            /**
             * Is Partial
             * @description True when a declared entity could not be included
             */
            is_partial: boolean;
            /** Reporting Currency */
            reporting_currency: string;
            total?: components["schemas"]["Money"] | null;
        };
        /**
         * Outcome
         * @description WLC's own vocabulary, mirrored so callers never see a raw exit code.
         * @enum {string}
         */
        Outcome: "ok" | "attention" | "refused" | "failed";
        /** PositionRow */
        PositionRow: {
            /** Account Id */
            account_id?: string | null;
            /** As Of */
            as_of?: string | null;
            /** Asset Class */
            asset_class?: string | null;
            /** Basis */
            basis?: string | null;
            /** Entity Id */
            entity_id: string;
            /** Entity Label */
            entity_label: string;
            identifier: components["schemas"]["Identifier"];
            /** Name */
            name?: string | null;
            /** Quantity */
            quantity?: number | null;
            value: components["schemas"]["Money"];
        };
        /** Positions */
        Positions: {
            /** As Of */
            as_of?: string | null;
            /**
             * Excluded
             * @default []
             */
            excluded: components["schemas"]["Excluded"][];
            /**
             * Granularity
             * @constant
             */
            granularity: "positions";
            /** Is Partial */
            is_partial: boolean;
            /** Reporting Currency */
            reporting_currency: string;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["PositionRow"][];
        };
        /** StoreInfo */
        StoreInfo: {
            availability: components["schemas"]["Availability"];
            /** Entity Id */
            entity_id: string;
            /** Schema Version */
            schema_version?: string | null;
            /** Workspace */
            workspace: string;
        };
        /** TransactionRow */
        TransactionRow: {
            /** Account Id */
            account_id?: string | null;
            /** @description Signed: negative left the household */
            amount: components["schemas"]["Money"];
            balance: components["schemas"]["Money"];
            /** Bank */
            bank?: string | null;
            /** Date */
            date?: string | null;
            /** Entity Id */
            entity_id: string;
            /** Entity Label */
            entity_label: string;
            /** Narration */
            narration?: string | null;
        };
        /** Transactions */
        Transactions: {
            /** As Of */
            as_of?: string | null;
            /**
             * Excluded
             * @default []
             */
            excluded: components["schemas"]["Excluded"][];
            /**
             * Granularity
             * @constant
             */
            granularity: "transactions";
            /** Is Partial */
            is_partial: boolean;
            /** Reporting Currency */
            reporting_currency: string;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["TransactionRow"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Version */
        Version: {
            engine: components["schemas"]["EngineInfo"];
            /**
             * Stores
             * @default []
             */
            stores: components["schemas"]["StoreInfo"][];
        };
        /** WorkspaceInfo */
        WorkspaceInfo: {
            availability: components["schemas"]["Availability"];
            /** Detail */
            detail?: string | null;
            holder?: components["schemas"]["Holder"] | null;
            /** Label */
            label: string;
            /** Schema Version */
            schema_version?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    start_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_status_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_stream_api_jobs__job_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    networth_api_networth_get: {
        parameters: {
            query?: {
                on?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetWorth"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    positions_api_positions_get: {
        parameters: {
            query?: {
                on?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Positions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transactions_api_transactions_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transactions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
}
